// Generated by CoffeeScript 2.1.1
(function() {
  var app;

  app = angular.module('example.app.photos', ['example.api']);

  app.controller('AppController', [
    '$scope',
    'Post',
    'PostPhoto',
    function($scope,
    Post,
    PostPhoto) {
      $scope.photos = {};
      $scope.posts = Post.query();
      return $scope.posts.$promise.then(function(results) {
        // Load the photos
        return angular.forEach(results,
    function(post) {
          return $scope.photos[post.id] = PostPhoto.query({
            post_id: post.id
          });
        });
      });
    }
  ]);

}).call(this);
