// Generated by CoffeeScript 2.1.1
(function() {
  var app;

  app = angular.module('example.app.basic', []);

  app.controller('AppController', [
    '$scope',
    '$http',
    function($scope,
    $http) {
      $scope.posts = [];
      return $http.get('/api/posts').then(function(result) {
        return angular.forEach(result.data,
    function(item) {
          return $scope.posts.push(item);
        });
      });
    }
  ]);

}).call(this);
