// Generated by CoffeeScript 2.1.1
(function() {
  var app;

  app = angular.module('example.api', ['ngResource']);

  app.factory('User', [
    '$resource',
    function($resource) {
      return $resource('/api/users/:username',
    {
        username: '@username'
      });
    }
  ]);

  app.factory('Post', [
    '$resource',
    function($resource) {
      return $resource('/api/posts/:id',
    {
        id: '@id'
      });
    }
  ]);

  app.factory('Photo', [
    '$resource',
    function($resource) {
      return $resource('/api/photos/:id',
    {
        id: '@id'
      });
    }
  ]);

  // And the nested resources
  app.factory('UserPost', [
    '$resource',
    function($resource) {
      return $resource('/api/users/:username/posts/:id');
    }
  ]);

  app.factory('PostPhoto', [
    '$resource',
    function($resource) {
      return $resource('/api/posts/:post_id/photos/:id');
    }
  ]);

}).call(this);
